### ISSUE TITLE
Completely meaningless results

### ISSUE THREAD

**Issue by BlaM** [mreschke/node-vs-php-vs-go#1]
Sorry, but the results you're publishing are somewhat meaningless.

For a start: Node.js uses just one CPU core, PHP/nginx uses all four. Don't know about Go. To make this comparable you should at least give node a chance and start four processes. You'll need some kind of load balancer then, though. So maybe node/nginx?

**Comment by zygis** [comment]
+1
Go 1.5.x uses all cpu available by default, 1.4.x and lower uses 1 cpu by default

**Comment by mreschke** [comment]
Thanks, Ill make a note of that and add alternate results.  My use case would be a microservice from within a docker container...ill have to test it within equally constrained containers.
