### ISSUE TITLE
Go and NodeJS doesn't utilize all the cores on your machine

### ISSUE THREAD

**Issue by ErhanAbi** [mreschke/node-vs-php-vs-go#5]
Your tests are unfair because both NodeJS and Golang doesn't leverage all the cores on your machine.

For node you can at least use the cluster module.

And for go you can simply use this in your main function.

``` go
import "runtime"

func main() {
    runtime.GOMAXPROCS(runtime.NumCPU())
    // rest of the code goes here
}
```

But I'm surprized by the php7 perf though. 👍 Good Job :)

**Comment by borislemke** [comment]
@pfzero Check this out. I made my own test on my development MacBook.
Node.js is waaaay faster than PHP
https://github.com/borislemke/nodejs_vs_php

**Comment by mreschke** [comment]
Yes thats why I put the note `NOTICE: These results are not accurate while using multi-core at the moment`.  I will be re-working the benchmark with this and more in mind soon.  Thanks.
